Resources:
  foods:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.foodsTable}
      AttributeDefinitions:
        - AttributeName: letter
          AttributeType: S
        - AttributeName: foodName
          AttributeType: S
      KeySchema:
        - AttributeName: letter
          KeyType: HASH
        - AttributeName: foodName
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST

  users:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.usersTable}
      AttributeDefinitions:
        - AttributeName: userID
          AttributeType: S
        - AttributeName: menuID
          AttributeType: S
      KeySchema:
        - AttributeName: userID
          KeyType: HASH
        - AttributeName: menuID
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
